import "IMessage.idl";
namespace Episode13
{
    [default_interface]
    runtimeclass UserControl2 : Microsoft.UI.Xaml.Controls.UserControl, IMessage
    {
        UserControl2();
        Int32 MyProperty;
    }
}
